FROM ros:humble-ros-base-jammy

ARG ROS_UID=1000
ARG ROS_GID=1000

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
      iputils-ping \
      python3-colcon-common-extensions \
      ros-humble-controller-manager \
      ros-humble-hardware-interface \
      ros-humble-joint-state-broadcaster \
      ros-humble-joint-state-publisher-gui \
      ros-humble-joint-trajectory-controller \
      ros-humble-moveit-configs-utils \
      ros-humble-moveit-kinematics \
      ros-humble-moveit-planners \
      ros-humble-moveit-ros-move-group \
      ros-humble-moveit-ros-visualization \
      ros-humble-moveit-setup-assistant \
      ros-humble-moveit-simple-controller-manager \
      ros-humble-pluginlib \
      ros-humble-robot-state-publisher \
      ros-humble-ros2-control-test-assets \
      ros-humble-rosidl-default-generators \
      ros-humble-rviz2 \
      ros-humble-tf2-ros \
      ros-humble-urdf \
      ros-humble-xacro \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd --gid "${ROS_GID}" ros \
    && useradd --uid "${ROS_UID}" --gid "${ROS_GID}" --create-home --shell /bin/bash ros \
    && mkdir -p /ros2_ws/build /ros2_ws/install /ros2_ws/log /ros2_ws/src \
    && chown -R "${ROS_UID}:${ROS_GID}" /ros2_ws /home/ros

COPY ros2_entrypoint.sh /ros2_entrypoint.sh

RUN chmod +x /ros2_entrypoint.sh \
    && printf '%s\n' \
      'source /opt/ros/humble/setup.bash' \
      '[ ! -f /ros2_ws/install/setup.bash ] || source /ros2_ws/install/setup.bash' \
      >> /etc/bash.bashrc

ENV HOME=/home/ros

USER ros
WORKDIR /ros2_ws
ENTRYPOINT ["/ros2_entrypoint.sh"]
CMD ["bash", "-lc", "sleep infinity"]
